version: '3.9'
name: 'assistify-dev'
services:
  backend:
    build:
      context: .
      target: dev
      dockerfile: ./apps/backend/Dockerfile.backend
    ports:
      - '3000:3000'
    volumes:
      - ./apps/backend/:/app/apps/backend/
      - /app/apps/backend/node_modules
    networks:
      - assistify-network
    environment:
      - PORT=3000
      - DATABASE_URL=mysql://root:@mysql-database:3306/assistify
    depends_on:
      mysql-database:
        condition: service_healthy

  mysql-database:
    image: mysql:8.2
    ports:
      - '3306:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
    environment:
      MYSQL_DATABASE: assistify
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - mysql_data:/app/mysql
    networks:
      - assistify-network

volumes:
  mysql_data:

networks:
  assistify-network:
    driver: bridge
